### PR TITLE
tidy up firmware version display

### PR DESCRIPTION
**Pull request by ukscone**
tidy up the firmware version display slightly

### CODE REVIEW

**Comment by shawaj** [comment]
Does this just lone wrap it @ukscone ?

**Comment by ukscone** [comment]
just split the string on DSP: and print the 2 halves on two lines. not great but does the job. tried a few other things like splitting on ';' and printing on separate lines but not great either

**Comment by shawaj** [comment]
Makes sense. Better than a huge overhang anyway. Not entirely sure why the version number is so long in the first place

**Comment by shawaj** [comment]
Looks good to me @ukscone - only thing I noticed is a rogue semi colon still left at the end of the first line?

2017-06-19-135217_1680x1050_scrot

**Comment by shawaj** [comment]
added the semicolon in front of DSP on your line 96 to get rid of it. 

And now merged. Thanks @ukscone

**Comment by ukscone** [comment]
I think from looking at the line a bit that the semicolons are the delimiters between key pairs. if you look at them after the first number they are all xxx:yyyy; . the ; before the DSP seems to be the end of the 'x:         ' pair. ok it doesn't matter but does seem interesting and possible to break down that line into meaningful things eventually

**Comment by shawaj** [comment]
Good spot. Will do some digging and see if we can find out what it all means

**Pull request merged**
