### PR TITLE
Improvement for screenly demo

### PR DESCRIPTION
**Pull request by antonmolodykh**
I think this will work better. in any case I have little experience with Flick so check if it makes sense

### CODE REVIEW

**Comment by vpetersson** [comment]
LGTM

**Comment by shawaj** [comment]
@tvoverbeek @francesco-vannini can you test with a Flick?

Or @vpetersson @antonmolodykh did you already test?

**Comment by antonmolodykh** [comment]
@shawaj I tested this with Flick

**Comment by tvoverbeek** [comment]
See my requested changes.
The original code is very sensitive to small movements since XYZ is reported continuously.
Using flicks makes more sense to change slides.

**Comment by antonmolodykh** [comment]
@tvoverbeek  thanks for the comments, I made corrections.

**Comment by tvoverbeek** [comment]
Merged. @antonmolodykh thanks

**Pull request merged**
